- type: entity
  id: TechFabMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: techfab machine board
  description: A machine printed circuit board for a generic techfab.
  components:
    - type: Sprite
      state: generic
    - type: MachineBoard
      prototype: TechFab
      requirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker

- type: entity
  id: TelecomServerShuttleCircuitboard
  parent: TelecomServerCircuitboard
  name: telecommunications array machine board
  description: A machine printed circuit board for an shipbound telecommunications array
  components:
  - type: Sprite
    state: engineering
  - type: MachineBoard
    prototype: TelecomServerShuttle
    stackRequirements:
      Steel: 1
      Cable: 2
